"""refresh tokens and dictionary indexes

Revision ID: 120ef128b81c
Revises: cc259417c8ae
Create Date: 2026-08-08 17:20:05.887822

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

# Required: autogenerate renders `sqlmodel.sql.sqltypes.AutoString()` for every
# str column, so without this import every generated migration dies on NameError.
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "120ef128b81c"
down_revision: str | Sequence[str] | None = "cc259417c8ae"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


_TIMESTAMP_COLUMNS = {
    "users": ("created_at", "updated_at"),
    "dictionary_entries": ("created_at", "updated_at"),
    "travel_history": ("created_at", "visit_date"),
    "places": ("created_at",),
    "culture_tips": ("created_at",),
    "emergency_contacts": (),
}


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "refresh_tokens",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("token_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        # No server_default: the table is created in this same revision, so
        # there are no existing rows to backfill, and declaring one here without
        # declaring it on the model shows up forever as schema drift.
        sa.Column("purpose", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("replaced_by", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("user_agent", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_refresh_tokens_token_hash"), "refresh_tokens", ["token_hash"], unique=True
    )
    op.create_index(op.f("ix_refresh_tokens_user_id"), "refresh_tokens", ["user_id"], unique=False)
    op.create_index(op.f("ix_refresh_tokens_purpose"), "refresh_tokens", ["purpose"])
    # ### end Alembic commands ###

    # Every dictionary read filters on user_id, and it had no index - a
    # sequential scan per request.
    op.create_index(
        "ix_dictionary_entries_user_id", "dictionary_entries", ["user_id"], unique=False
    )
    # Search does `ilike('%term%')`, which no btree index can serve. pg_trgm
    # makes those leading-wildcard matches indexable.
    op.execute(
        "CREATE INDEX ix_dictionary_entries_word_trgm "
        "ON dictionary_entries USING gin (word gin_trgm_ops)"
    )
    op.execute(
        "CREATE INDEX ix_dictionary_entries_translation_trgm "
        "ON dictionary_entries USING gin (translation gin_trgm_ops)"
    )
    # Place search covers these four columns with the same pattern.
    op.execute("CREATE INDEX ix_places_name_trgm ON places USING gin (name gin_trgm_ops)")
    op.execute("CREATE INDEX ix_places_city_trgm ON places USING gin (city gin_trgm_ops)")
    # Guide and place listings filter on these.
    op.create_index("ix_places_country_category", "places", ["country", "category"])
    op.create_index("ix_culture_tips_country_language", "culture_tips", ["country", "language"])
    op.create_index("ix_emergency_contacts_country", "emergency_contacts", ["country", "is_active"])

    # Timestamps were TIMESTAMP WITHOUT TIME ZONE while the application writes
    # timezone-aware values, so the offset was silently dropped on write and any
    # comparison against an aware `utcnow()` raised. Existing rows are already
    # UTC, so this reinterprets rather than shifts them.
    for table, columns in _TIMESTAMP_COLUMNS.items():
        for column in columns:
            op.execute(
                f"ALTER TABLE {table} ALTER COLUMN {column} "
                f"TYPE TIMESTAMPTZ USING {column} AT TIME ZONE 'UTC'"
            )


def downgrade() -> None:
    """Downgrade schema."""
    for table, columns in _TIMESTAMP_COLUMNS.items():
        for column in columns:
            op.execute(f"ALTER TABLE {table} ALTER COLUMN {column} TYPE TIMESTAMP USING {column}")
    op.drop_index("ix_emergency_contacts_country", table_name="emergency_contacts")
    op.drop_index("ix_culture_tips_country_language", table_name="culture_tips")
    op.drop_index("ix_places_country_category", table_name="places")
    op.execute("DROP INDEX IF EXISTS ix_places_city_trgm")
    op.execute("DROP INDEX IF EXISTS ix_places_name_trgm")
    op.execute("DROP INDEX IF EXISTS ix_dictionary_entries_translation_trgm")
    op.execute("DROP INDEX IF EXISTS ix_dictionary_entries_word_trgm")
    op.drop_index("ix_dictionary_entries_user_id", table_name="dictionary_entries")
    # pg_trgm is left installed: other objects may depend on it.
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_refresh_tokens_purpose"), table_name="refresh_tokens")
    op.drop_index(op.f("ix_refresh_tokens_user_id"), table_name="refresh_tokens")
    op.drop_index(op.f("ix_refresh_tokens_token_hash"), table_name="refresh_tokens")
    op.drop_table("refresh_tokens")
    # ### end Alembic commands ###
