"""place favourites

Revision ID: b22242681583
Revises: 120ef128b81c
Create Date: 2026-08-08 23:33:43.147467

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
# Required: autogenerate renders `sqlmodel.sql.sqltypes.AutoString()` for every
# str column, so without this import every generated migration dies on NameError.


# revision identifiers, used by Alembic.
revision: str = "b22242681583"
down_revision: str | Sequence[str] | None = "120ef128b81c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "place_favorites",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("place_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["place_id"],
            ["places.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "place_id", name="uq_place_favorites_user_place"),
    )
    op.create_index(
        op.f("ix_place_favorites_place_id"), "place_favorites", ["place_id"], unique=False
    )
    op.create_index(
        op.f("ix_place_favorites_user_id"), "place_favorites", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_place_favorites_user_id"), table_name="place_favorites")
    op.drop_index(op.f("ix_place_favorites_place_id"), table_name="place_favorites")
    op.drop_table("place_favorites")
    # ### end Alembic commands ###
