"""initial schema

Revision ID: cc259417c8ae
Revises:
Create Date: 2026-08-08 12:49:27.838498

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

# Required: autogenerate renders `sqlmodel.sql.sqltypes.AutoString()` for every
# str column, so without this import every generated migration dies on NameError.
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "cc259417c8ae"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # Needed by the trigram indexes added in a later revision, and by
    # SQLModel.metadata.create_all, which builds every declared index at once.
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "culture_tips",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("country", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("tip_category", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("tip_text", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("language", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("importance", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "emergency_contacts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("country", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("service_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("number", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "places",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("country", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("state", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("city", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.Column("category", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("images", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("languages_spoken", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("best_time_to_visit", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("entry_fee", sa.Float(), nullable=True),
        sa.Column("rating", sa.Float(), nullable=True),
        sa.Column("cultural_info", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("emergency_contacts", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("local_customs", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("username", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("password_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("full_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("profile_picture", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("preferred_language", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("preferred_theme", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("home_country", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.create_table(
        "dictionary_entries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("word", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("translation", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("language_from", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("language_to", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("pronunciation", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("usage_example", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("tags", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("is_favorite", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "travel_history",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("destination", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("country", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("visit_date", sa.DateTime(), nullable=False),
        sa.Column("notes", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("photos", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("favorite_phrases", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("rating", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###

    # `rating` is declared `Field(ge=1, le=5)` on both models, but that is a
    # pydantic-only constraint: it validates objects constructed in Python and
    # does nothing for seeds, bulk loads or raw SQL. Enforce it in the database.
    op.create_check_constraint(
        "ck_places_rating_range", "places", "rating IS NULL OR (rating >= 1 AND rating <= 5)"
    )
    op.create_check_constraint(
        "ck_travel_history_rating_range",
        "travel_history",
        "rating IS NULL OR (rating >= 1 AND rating <= 5)",
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint("ck_travel_history_rating_range", "travel_history", type_="check")
    op.drop_constraint("ck_places_rating_range", "places", type_="check")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("travel_history")
    op.drop_table("dictionary_entries")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_table("places")
    op.drop_table("emergency_contacts")
    op.drop_table("culture_tips")
    # ### end Alembic commands ###
